apiVersion: v1
kind: Secret
metadata:
  name: webhooks-api-secrets
type: Opaque
stringData:
  ConnectionStrings__webhooksdb: "Host=postgres;Port=5432;Database=webhooksdb;Username=postgres;Password=Changeme"
  ConnectionStrings__eventbus: "amqp://eshop_rabbit:password@rabbitmq:5672/"
