apiVersion: v1
kind: Secret
metadata:
  name: identity-api-secrets
type: Opaque
stringData:
  ConnectionStrings__identitydb: "Host=postgres;Port=5432;Database=identitydb;Username=postgres;Password=Changeme"
