apiVersion: v1
kind: Service
metadata:
  name: identity-api-external
spec:
  selector:
    app: identity-api
  ports:
    - port: 5223
      targetPort: 8080
      nodePort: 5223
  type: NodePort
