image:
  repository: ghcr.io/josuekabangu/basket-api
  tag: latest

replicaCount: 1

redis:
  host: redis
  port: 6379
  password: changeme

rabbitmq:
  host: rabbitmq
  port: 5672
  username: eshop_rabbit
  password: password

identity:
  url: "http://identity-api:8080"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

probes:
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 20
