apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secrets
type: Opaque
stringData:
  ConnectionStrings__catalogdb: "Host=postgres;Port=5432;Database=catalogdb;Username=postgres;Password=Changeme"
  ConnectionStrings__eventbus: "amqp://eshop_rabbit:password@rabbitmq:5672/"
