apiVersion: v1
kind: Secret
metadata:
  name: ordering-api-secrets
type: Opaque
stringData:
  ConnectionStrings__orderingdb: "Host=postgres;Port=5432;Database=orderingdb;Username=postgres;Password=Changeme"
  ConnectionStrings__eventbus: "amqp://eshop_rabbit:password@rabbitmq:5672/"
