apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordering-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordering-api
  template:
    metadata:
      labels:
        app: ordering-api
    spec:
      containers:
        - name: ordering-api
          image: ghcr.io/josuekabangu/ordering-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ordering-api-config
          env:
            - name: ConnectionStrings__orderingdb
              valueFrom:
                secretKeyRef:
                  name: ordering-api-secrets
                  key: ConnectionStrings__orderingdb
            - name: ConnectionStrings__eventbus
              valueFrom:
                secretKeyRef:
                  name: ordering-api-secrets
                  key: ConnectionStrings__eventbus
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
