apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: "ZXNob3BfcmFiYml0"    # "eshop_rabbit" | base64
  RABBITMQ_DEFAULT_PASS: "cGFzc3dvcmQ="        # "password" | base64
