apiVersion: v1
kind: Service
metadata:
  name: webhook-client-external
spec:
  selector:
    app: webhook-client
  ports:
    - port: 5114
      targetPort: 8080
      nodePort: 5114
  type: NodePort
