apiVersion: v1
kind: Secret
metadata:
  name: basket-api-secrets
type: Opaque
stringData:
  ConnectionStrings__redis: "redis:6379,password=changeme"
  ConnectionStrings__eventbus: "amqp://eshop_rabbit:password@rabbitmq:5672/"
