apiVersion: v1
kind: Service
metadata:
  name: basket-api
spec:
  selector:
    app: basket-api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP    # gRPC tourne sur HTTP/2, mais reste du TCP au niveau du Service K8s
  type: ClusterIP
