image: redis:7

replicaCount: 1

redis:
  password: changeme
  maxmemory: 1gb
  maxmemoryPolicy: allkeys-lru

storage: 
  size: 1Gi

probes:
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
  
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 3
