apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.user }}   
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.password }}        

